### ISSUE TITLE
Remove redundant segments from paths

### ISSUE THREAD

**Issue by StevenLiekens** [jonschlinkert/normalize-path#6]
I'm looking for a library that removes as many path segments as possible without changing the meaning of the path.

- `/foo/./bar` -> `/foo/bar`
- `./../foo` -> `../foo`
- `./foo/../bar` -> `./bar`

etc

**Comment by jonschlinkert** [comment]
I can see how that would make sense given the name of the lib, but it seems like that would be a better job for node's native `path.normalize()` method, wouldn't it?

**Comment by StevenLiekens** [comment]
I don't know, I can't find a good definition of the scope of this library.

**Comment by StevenLiekens** [comment]
Anyway I guess it depends on whether you consider variations of a path to be duplicates or not.

Personally I think it's confusing that small variations return different output from normalize.

```js
normalize('ayy/') !== normalize('./ayy/') // weird
```

**Comment by jonschlinkert** [comment]
> I don't know, I can't find a good definition of the scope of this library.

Maybe try reading the actual repository description? I'll quote it here: "Normalize slashes in a file path to be posix/unix-like forward slashes. Also condenses repeat slashes to a single slash and removes and trailing slashes, unless disabled."

I'm not sure how it could be any less confusing. 

> `normalize('ayy/') !== normalize('./ayy/') // weird`

```js
console.log(normalize('ayy/'))   //=> "ayy"
console.log(normalize('./ayy/')) //=> "./ayy"
```

Given how clearly defined the repository description is, it's weird that you find that weird. 

Closing.

**Comment by sliekens** [comment]
Describing what the code currently does is not what I consider defining its scope because it says nothing about which problems you're trying to solve. But no need to be salty. Just reply to my comment after that (from the perspective of someone who doesn't know exactly how your function is implemented).

PS didn't mean to offend, I'm just saying that the verb "to normalize" is very loosely defined. It can mean basically anything you want it to so whether this feature is in scope really depends on your interpretation.

PPS my take on this is that when two different paths resolve to the same file or folder, their normal forms should be equal strings. I know that's not always possible, but in this case it is.
